//module included in the following assembly:
//
// *networking/multiple_networks/understanding-user-defined-networks.adoc

:_mod-docs-content-type: PROCEDURE
[id="nw-udn-cr_{context}"]
= Creating a UserDefinedNetwork custom resource

The following procedure creates a user-defined network that is namespace scoped. Based upon your use case, create your request using either the `my-layer-two-udn.yaml` example for a `Layer2` topology type or the `my-layer-three-udn.yaml` example for a `Layer3` topology type.

//We won't have these pieces till GA in 4.18.
//[NOTE]
//====
//If any cluster default networked pods exist before the user-defined network is created, any further pods created in this namespace will return an error message: `What_is_this`.
//====

.Procedure

. Create a request for either a `Layer2` or `Layer3` topology type user-defined network:

.. Create a YAML file, such as `my-layer-two-udn.yaml`, to define your request for a `Layer2` topology as in the following example:
+
[source, yaml]
----
apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
  name: udn-1 # <1>
  namespace: <some_custom_namespace>
spec:
  topology: Layer2 # <2>
  layer2: <3>
    role: Primary # <4>
    mtu: 9000 # <5>
    subnets:
      - "10.0.0.0/24"
      - "2001:db8::/60" # <6>
----
<1> Name of your `UserDefinedNetwork` resource. This should not be `default` or duplicate any global namespaces created by the Cluster Network Operator (CNO).
<2> The `topology` field describes the network configuration; accepted values are `Layer2` and `Layer3`. Specifying a `Layer2` topology type creates one logical switch that is shared by all nodes.
<3> This field specifies the topology configuration, it can be `layer2` or `layer3`.
<4> Specifies `Primary` or `Secondary`. `Primary` is the only `role` specification supported in {product-version}.
<5> The maximum transmission units (MTU) is an optional field. The default value is `1400`. The boundary for IPv4 is `574`, and for IPv6 it is `1280`.
<6> For `Layer2` topology types the following specifies config details for the `subnet` field:
+
* The subnets field is optional.
* The subnets field is of type `string` and accepts standard CIDR formats for both IPv4 and IPv6.
* The subnets field accepts one or two items. For two items, they must be of a different family. For example, subnets values of `10.100.0.0/16` and `2001:db8::/64`.
* `Layer2` subnets can be omitted. If omitted, users must configure IP addresses for the pods. As a consequence, port security only prevents MAC spoofing.
* The `Layer2` `subnets` field is mandatory when the `ipamLifecycle` field is specified.
+
[NOTE]
====
There are two additional configurations that UDN uses: `spec.joinSubnets` and `spec.IPAMlifecycle`. It is not recommended to set these fields without explicit need and understanding of the OVN network topology.

When omitted, the platform sets default values for the `joinSubnets` field of `100.65.0.0/16` for IPv4 and  `fd99::/64` for IPv6. If the default address values are used anywhere in the cluster's network you must override it by setting the `joinSubnets` field. If you choose to set this field, ensure it does not conflict with other subnets in the cluster such as the cluster subnet, the `default` network cluster subnet, and the masquerade subnet.

The `joinSubnets` field configures the routing between different segments within the Layer 2 network. Dual-stack clusters can set 2 subnets, one for each IP family; otherwise, only 1 subnet is allowed. This field is only allowed for the `Primary` network.

The `IPAMLifecycle` field configures the IP address management system (IPAM). You might use this field for virtual workloads to ensure persistent IP addresses. This field is allowed when `topology` is `layer2`. The `subnets` field must be specified when this field is specified. Setting a value of `Persistent` ensures that your virtual workloads have persistent IP addresses across reboots and migration. These are assigned by the container network interface (CNI) and used by OVN-Kubernetes to program pod IP addresses. You must not change this for pod annotations.
====

.. Create a YAML file, such as `my-layer-three-udn.yaml`, to define your request for a `Layer3` topology as in the following example:
+
[source, yaml]
----
apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
  name: udn-2-primary # <1>
  namespace: <some_custom_namespace>
spec:
  topology: Layer3 # <2>
  layer3: # <3>
    role: Primary # <4>
    mtu: 1300 # <5>
    subnets: # <6>
      - cidr: 10.150.0.0/16
        hostSubnet: 24
      - cidr: 2001:db8::/60
        hostSubnet: 64
----
<1> Name of your `UserDefinedNetwork` resource. This should not be `default` or duplicate any global namespaces created by the Cluster Network Operator (CNO).
<2> The `topology` field describes the network configuration; accepted values are `Layer2` and `Layer3`. Specifying a `Layer3` topology type creates a layer 2 segment per node, each with a different subnet. Layer 3 routing is used to interconnect node subnets.
<3> This field specifies the topology configuration. Valid values are `layer2` or `layer3`.
<4> Specifies a `Primary` or `Secondary` role. `Primary` is the only `role` specification supported in 4.17 .
<5> The maximum transmission units (MTU) is an optional field. The default value is `1400`. The boundary for IPv4 is `574`, and for IPv6 it is `1280`.
<6> For `Layer3` topology types the following specifies config details for the `subnet` field:
+
* The `subnets` field is mandatory.
* The type for the `subnets` field is `cidr` and `hostSubnet`:
** `cidr` is the cluster subnet and accepts a string value.
** `hostSubnet` specifies the nodes subnet prefix that the cluster subnet is split to.
** For IPv6, only a `/64` length is supported for `hostSubnet`.
+
[NOTE]
====
There is an additional configuration that UDN uses for a `Layer3` topology: `spec.joinSubnets`. It is not recommended to set this field without explicit need and understanding of the OVN network topology.

When omitted, the platform sets as a default value for IPv4 `100.65.0.0/16` and for IPv6 `fd99::/64`. If the default address values are used anywhere in the cluster's network you must override it by setting the `joinSubnets` field. If you choose to set this field, ensure it does not conflict with other subnets in the cluster such as the cluster subnet, the `default` network cluster subnet, and the masquerade subnet.

The `joinSubnets` field configures the routing between different segments within the Layer 2 network. Dual-stack clusters may set 2 subnets, one for each IP family; otherwise, only 1 subnet is allowed. This field is only allowed for the `Primary` network.
====

.. Apply your request by running the following command:
+
[source,terminal]
----
$ oc apply -f <my_layer_two_udn.yaml>
----
+
Where `<my_layer_two_udn.yaml>` is the name of your `Layer2` or `Layer3` configuration file.

. Verify that your request is successful by running the following command:
+
[source, terminal]
----
$ oc get userdefinednetworks udn-1 -n <some_custom_namespace> -o yaml
----
+
Where `some_custom_namespace` is the namespace you created for your user-defined network.
+
.Example output
[source,terminal]
----
apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
  creationTimestamp: "2024-08-28T17:18:47Z"
  finalizers:
  - k8s.ovn.org/user-defined-network-protection
  generation: 1
  name: udn-1
  namespace: some-custom-namespace
  resourceVersion: "53313"
  uid: f483626d-6846-48a1-b88e-6bbeb8bcde8c
spec:
  layer2:
    mtu: 9000
    role: Primary
    subnets:
    - 10.0.0.0/24
    - 2001:db8::/64
  topology: Layer2
status:
  conditions:
  - lastTransitionTime: "2024-08-28T17:18:47Z"
    message: NetworkAttachmentDefinition has been created
    reason: NetworkAttachmentDefinitionReady
    status: "True"
    type: NetworkReady
----

