:_mod-docs-content-type: ASSEMBLY
[id="about-bgp-routing"]
= About BGP routing
include::_attributes/common-attributes.adoc[]
:context: about-bgp-routing

toc::[]

This feature provides native Border Gateway Protocol (BGP) routing capabilities for the cluster.

The following information applies when you integrate BGP with MetalLB and FRR-K8s on the cluster.

[IMPORTANT]
====
If you are using the MetalLB Operator and there are existing `FRRConfiguration` CRs in the `metallb-system` namespace created by cluster administrators or third-party cluster components other than the MetalLB Operator, you must ensure that they are copied to the `openshift-frr-k8s` namespace or that those third-party cluster components use the new namespace. For more information, see xref:../../../networking/advanced_networking/bgp_routing/migrating-frr-k8s-resources.adoc#migrating-frr-k8s-resources[Migrating FRR-K8s resources].
====

include::modules/nw-bgp-about.adoc[leveloffset=+1]

include::modules/nw-metallb-frr-k8s-configuration-crd.adoc[leveloffset=+1]

include::modules/nw-no-overlay-overview.adoc[leveloffset=+1]

[role="_additional-resources"]
[id="additional-resources_about-bgp-routing"]
== Additional resources

- link:https://docs.frrouting.org/en/latest/bgp.html[FRRouting User Guide: BGP]
- xref:../../advanced_networking/bgp_routing/no-overlay-mode-bgp-routing.adoc#no-overlay-mode-bgp-routing[Improve east-west performance by routing pods on the underlay with BGP]
